### ISSUE TITLE
"Saved Passkey" vs "Touch ID Passkey": What's the difference?

### ISSUE THREAD

**Issue by coolaj86** [mylofi/webauthn-local-client#12]
I don't know what it's like on other operating systems, but on macOS the user experience is nicer with Touch ID Passkeys rather than Saved Passkeys - the modal window opens in the correct place rather than potentially on another screen.

Do you know what the difference is between triggering the two different types of passkey?

Also, clicking **Use a different passkey** doesn't show the Touch ID Passkey option.

This is, of course, very confusing because they both use the term "Touch ID" and the term "Passkey". One of them is "Browser" and the other is "Saved".

# Saved Passkey

<img width="760" alt="Screenshot 2024-08-28 at 8 23 40 PM" src="https://github.com/user-attachments/assets/7abe8a41-9b3b-4f9c-8963-41518e43c6b9">

<img width="372" alt="Screenshot 2024-08-28 at 8 23 46 PM" src="https://github.com/user-attachments/assets/a74ea299-5e1f-493a-9661-05891130e15a">

# Touch ID

<img width="760" alt="Screenshot 2024-08-28 at 8 24 19 PM" src="https://github.com/user-attachments/assets/0ece4f6a-d86f-4f8e-98c0-63bf367f88e4">

<img width="760" alt="Screenshot 2024-08-28 at 8 24 22 PM" src="https://github.com/user-attachments/assets/a31f9887-2d70-440b-9229-a375f81356b7">

**Comment by getify** [comment]
Interesting, I don't have a mac so I haven't seen this UX myself. My instinct is to say it's up to the browser and OS, because the APIs we call just hand off the request to them. I don't think there's anything I'm sending which is affecting which of those modals shows up or which options are available.

**Comment by coolaj86** [comment]
It's the same (not-Safari) browser on the same OS and same user account etc, being tested with WebAuthn side-by-side on two different websites, so it's definitely a difference in options.

I'm thinking it's related to either "UV required" or the option to show a list of initial options vs showing the os-default option only.

I highly doubt it's a different non-WebAuthn API because Apple never lets 3rd party apps use their integrated APIs, and this isn't Safari.

**Comment by getify** [comment]
> I highly doubt it's a different non-WebAuthn API because Apple never lets 3rd party apps use their integrated APIs, and this isn't Safari.

Websites wouldn't have different APIs, no. But I have definitely seen different UX from how different native apps (I use Android) integrate and use various native platform APIs.

> ...so it's definitely a difference in options.

OK, interesting. FWIW, we do in fact require some specific settings for the way we need the passkey to work... 

1. [`authenticatorAttachment`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions#authenticatorattachment) is set to `"platform"`, which means a built-in authenticator (like a FaceID camera or a TouchID scanner), as opposed to `"cross-platform"` which are external authenticators like USB sticks, etc. This is required/strongly-preferred because many of the external authenticators don't support the behavior we need (the `userHandle` retrieval, discoverable passkeys, etc).

2. [`residentKey`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions#residentkey) is set to `"required"`, because we need to support discoverable passkeys (meaning where you are authenticating but don't already know the credential-ID, so the browser needs to prompt the user to select a passkey (among possibly multiple registered ones).

    Technically, this is an *optional* setting, because you could limit usage to where you only ever store and know about passkeys. But I think this will be worse UX for users in the cases where such a credential ID might be forgotten (like if storage was cleared).

    A sub-setting related to this is [`requireResidentKey`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions#requireresidentkey), which is set to `true`.

3. [`userVerification`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions#userverification) tells the authenticator that it must actually affirmatively prompt and verify with the user, instead of just silently verifying in the background.

    This setting is probably the most important, because without UV, the passkey will not return the `userHandle` from the passkey upon successful authentication, and we have to have that value to re-derive the encryption keypair.

All of these settings can be overridden in the options that are passed to WebAuthn-Local-Client's [`register(..)`](https://github.com/mylofi/webauthn-local-client?tab=readme-ov-file#registering-a-new-credential) call. However, Local-Data-Lock's `getLockKey(..)` call does not currently support overriding these particular settings [for its underlying `register()` call](https://github.com/mylofi/local-data-lock/blob/1746aadd8c0f83a6860d7bb926169e764c97855c/src/ldl.js#L370-L380). Neither does Local-Vault's [`connect()` call](https://github.com/mylofi/local-vault?tab=readme-ov-file#setting-up-a-local-vault-instance) support overriding them [for its underlying `getLockKey(..)` call](https://github.com/mylofi/local-vault/blob/d06bcdef4c124eee2fffb4067dceb84823ff6674/src/lv.js#L109-L114).

It's possible we could revisit and potentially allow overriding these through Local-Data-Lock and Local-Vault APIs. But we have to make sure settings aren't overridden in a way that fundamentally breaks what's being assumed about how the passkeys / `userHandle`s work.

>  I'll update if I figure it out.

Yes, please do let me know if you figure anything specific out.

**Comment by coolaj86** [comment]
Interestingly, if I just click "Continue" then I get the "ugly" modal:

<img width="275" alt="Screenshot 2024-08-30 at 2 00 59 AM" src="https://github.com/user-attachments/assets/46fd8112-3fae-4aba-969c-87f3fb1d5bf3">

<img width="150" alt="Screenshot 2024-08-30 at 2 01 08 AM" src="https://github.com/user-attachments/assets/7d06416f-f03c-4212-872a-6471164dcab0">

But this particular demo gives the "Save Another Way" option, which I don't think was in the other demos:

<img width="275" alt="Screenshot 2024-08-30 at 2 01 33 AM" src="https://github.com/user-attachments/assets/2a72c08b-6433-4a11-98dc-355284b20426">

<img width="275" alt="Screenshot 2024-08-30 at 2 01 45 AM" src="https://github.com/user-attachments/assets/6b58003e-ffa5-4348-92a0-120b945b6c0d">

I'm not sure what to make of that. I wonder if it could be made the default.

**Comment by getify** [comment]
The UX (which modals you get) also will depend on which button/mode you're trying in the test demo page.

* The "setup vault" registers a new passkey, which presents a slightly different looking flow of modal prompts.

* The "unlock vault" and "discover vault" both try to unlock (via passkey authentication instead of new registration), but...

    - "unlock" passes a specific credential ID and tells the system to only use that specific passkey for the authentication... so the browser/system may skip or simplify its modal in such a case where only one specified passkey is allowed.

    - "discover" doesn't pass a credential-ID and instead asks the browser/system to present all "discoverable" (aka "resident") passkeys, so that modal prompt is likely going to look different since it has to show you potentially a list of various passkeys to choose from.

**Comment by coolaj86** [comment]
Okay, so I think I've figured it out. All of what you said, but a few extra details:

Options

- mediation
  - "optional" and "required" mean "please show the multi-auth prompt, maybe"
  - "conditional" means "mini-prompt on inputs with autocomplete="webauthn""
  - "silent" seems to be ignored
- user
  - seems to be ignored, except when registering
  - maybe used to skip the multi-auth prompt when silent is set?

Modes

- When 0 keys exist, 
- When exactly 1 passkey exists, `get(credOpts)` on macOS _always_ uses that key, always with biometrics, regardless of the options - unless it was created with the browser option, in which case it will do the uglier modal, with a password
- When 2+ passkeys exist, you can get the multi-auth to come up

There's _a lot_ of possible permutations here. I think I won't realistically discover many of them until user complaints surface.

**Comment by getify** [comment]
Potentially related: https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions#hints

**Comment by getify** [comment]
> "conditional" means "mini-prompt on inputs with autocomplete="webauthn""

BTW, if you haven't seen this: https://web.dev/articles/passkey-form-autofill

Conditional mediation is demo'd in the tests for this library (WebAuthn-Local-Client), but honestly... that UX flow -- clicking into a username/password field to activate auto-fill, instead of just clicking a button -- doesn't really match the expected UX of how I think apps will use local-data-lock and local-vault.

It seems like a "transitional UI" mode where you've got an app that users already do username/password authentication, and you're migrating/upgrading to passkeys (optionally)... so users can sort of figure out the passkey thing while interacting with an auth UI they're already familiar with.

**Comment by getify** [comment]
Also, while I agree that it matters how the UX of these modals feels to end-users, ultimately, I'm not inclined to obsess too much about it, or jump through too many hoops to affect what's shown.

The reason is similar to how I use standard HTML form elements (select boxes, checkboxes, calendar picker, etc) instead of super-customized UI elements. I actually think that sort of responsibility belongs to the browser/OS/device. It *should* be different for iOS users versus Android, etc. Because the makers of those devices have an entirely different relationship with their users, set different brand/UX expectations, etc. I think app developers should kind of yield control over in those cases, and let those makers own the responsibility to design good interaction UX.

**Comment by coolaj86** [comment]
I 100% agree that users on Android should be given the opportunity to have the Android experience, and users on Apple should be given the Apple experience.

And Chrome users, well, there doesn't seem to be a way to _force_ the Apple or Android experience to come first on Desktop - it's just always Chrome experience and the user has to personally click the button to opt-in to the Apple or Microsoft experience - which makes sense because Google doesn't want your keys on someone else's cloud. They need their fingers in there to divert the keys first and foremost to them, duh!

I hate these milktoast apps that in order to have "better" and "consistent" design end up with far worse design with the defaults provided by the platform, and completely inconsistent with user expectations.

I don't know if this will live and grow here for a long time, but this is my own demo:
<https://beyondcodebootcamp.github.io/vanilla-webauthn/>

I found that it's actually waaaaaaaaay simpler than almost everyone is explaining it, if you know a few critical details about how the system works.

It's definitely made to give Big Tech the advantage and to make it as close to as impossible as can be for Self-Sovereign Identity, but I've found a few loopholes that I think I can exploit for local encryption, and a few shortcuts to really simplify the DX based on how it works in practice rather than the 10,000 permutations that are spec'd, but that I can verify don't work.

Early next week I'll be having more people test on their phones and computers to make sure I've got it all right and that my implementation doesn't conflict with future variations of the standard, but I feel pretty confident that I could explain and demo it simply enough to, for example, make conference slides for it (too bad I didn't run into this months ago to submit to UtahJS).

Right now I believe that the best thing that Credential IDs can be used for is local encryption. As far as I can tell, the UX between "Register Passkey" and "Login with Passkey" is so constrained, that even if you sync the IDs through servers across devices, there's a lot of caveats and you're probably better off:
- tracking if signin has _ever_ happened on that device to show the "Login" button
- collecting IDs on sign-in to exclude them from accidental deletion 😱 🤦‍♂️ during "Register"
- not sending IDs to a server, because either you can't use them before the user logs in anyway, or you'll just be up exposing them for any bot to have

This actually seems a lot like some sort of "malicious compliance" - like this whole WebAuthn standard is _actually_ designed to put Big Tech in control, but with a really awesome marketing message about "the users" and "safety"... meanwhile the details of the implementation do not build a strong case for that. A little lip service in the spec, but Big Tech isn't actually implementing the bits that would serve us best.
